CREATE SCHEMA IF NOT EXISTS netmap;
CREATE TABLE IF NOT EXISTS netmap.cidrs (
  id SERIAL PRIMARY KEY,
  cidr TEXT UNIQUE NOT NULL,
  label TEXT NOT NULL DEFAULT '',
  enabled BOOLEAN NOT NULL DEFAULT true
);
CREATE TABLE IF NOT EXISTS netmap.hosts (
  ip INET PRIMARY KEY,
  mac TEXT NOT NULL DEFAULT '',
  hostname TEXT NOT NULL DEFAULT '',
  vendor TEXT NOT NULL DEFAULT '',
  cidr TEXT NOT NULL DEFAULT '',
  ports JSONB NOT NULL DEFAULT '[]',
  last_seen TIMESTAMPTZ NOT NULL DEFAULT now(),
  extra JSONB NOT NULL DEFAULT '{}'
);
CREATE TABLE IF NOT EXISTS netmap.scans (
  id SERIAL PRIMARY KEY,
  cidr TEXT NOT NULL,
  started TIMESTAMPTZ NOT NULL DEFAULT now(),
  finished TIMESTAMPTZ,
  hosts_found INT NOT NULL DEFAULT 0,
  log TEXT NOT NULL DEFAULT ''
);
