server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Avoid serving ops/ scripts as static by accident if requested
    location ^~ /ops/ {
        return 404;
    }
}
